# Generated by Django 3.1.4 on 2021-03-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login', '0005_auto_20210315_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userweight',
            name='expecet_weight',
        ),
        migrations.AlterField(
            model_name='userbloodpressure',
            name='bloodpressure',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userbloodsugar',
            name='bloodsugar',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userheight',
            name='height',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userwaist',
            name='waist',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userweight',
            name='weight',
            field=models.CharField(max_length=30),
        ),
    ]
