# Generated by Django 3.1.4 on 2021-03-15 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login', '0007_auto_20210315_2304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_test',
        ),
    ]
