from django.contrib import admin
from . import models

admin.site.register(models.Food01)
admin.site.register(models.Food02)
admin.site.register(models.Food03)
admin.site.register(models.Food04)
admin.site.register(models.Food05)
admin.site.register(models.Food06)
admin.site.register(models.Food07)
admin.site.register(models.Food08)
admin.site.register(models.Food09)
admin.site.register(models.Food10)
admin.site.register(models.Food11)
admin.site.register(models.Food12)
admin.site.register(models.Food13)
admin.site.register(models.Food14)
admin.site.register(models.Food15)
admin.site.register(models.Food16)
admin.site.register(models.Food17)
admin.site.register(models.Food18)
admin.site.register(models.Food19)
admin.site.register(models.Food20)
admin.site.register(models.Food21)
admin.site.register(models.FoodTypeList)
# Register your models here.
