# Generated by Django 3.2 on 2022-04-05 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
    ]
