# Generated by Django 3.1.4 on 2021-03-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login', '0008_delete_user_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userweight',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
