# Generated by Django 3.2 on 2022-04-04 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0003_author'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
