# Generated by Django 3.2 on 2022-04-04 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0005_auto_20220404_1157'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
    ]
