--------------------------------------------------------
--  文件已创建 - 星期日-三月-21-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FOOD_TYPE_LIST
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."FOOD_TYPE_LIST" 
   (	"TYPEID" VARCHAR2(26 BYTE), 
	"TYPENAME" VARCHAR2(128 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SYSTEM.FOOD_TYPE_LIST
SET DEFINE OFF;
Insert into SYSTEM.FOOD_TYPE_LIST (TYPEID,TYPENAME) values ('01','谷类及制品');
Insert into SYSTEM.FOOD_TYPE_LIST (TYPEID,TYPENAME) values ('02','薯类、淀粉及制品');
Insert into SYSTEM.FOOD_TYPE_LIST (TYPEID,TYPENAME) values ('03','干豆类及制品');
Insert into SYSTEM.FOOD_TYPE_LIST (TYPEID,TYPENAME) values ('04','蔬菜类及制品');
Insert into SYSTEM.FOOD_TYPE_LIST (TYPEID,TYPENAME) values ('05','菌藻类');
Insert into SYSTEM.FOOD_TYPE_LIST (TYPEID,TYPENAME) values ('06','水果类及制品');
Insert into SYSTEM.FOOD_TYPE_LIST (TYPEID,TYPENAME) values ('07','坚果、种子类');
Insert into SYSTEM.FOOD_TYPE_LIST (TYPEID,TYPENAME) values ('08','畜肉类及制品');
Insert into SYSTEM.FOOD_TYPE_LIST (TYPEID,TYPENAME) values ('09','禽肉类制品');
Insert into SYSTEM.FOOD_TYPE_LIST (TYPEID,TYPENAME) values ('10','乳类及制品');
Insert into SYSTEM.FOOD_TYPE_LIST (TYPEID,TYPENAME) values ('11','蛋黄及制品');
Insert into SYSTEM.FOOD_TYPE_LIST (TYPEID,TYPENAME) values ('12','鱼虾蟹贝类');
Insert into SYSTEM.FOOD_TYPE_LIST (TYPEID,TYPENAME) values ('13','婴幼儿食品');
Insert into SYSTEM.FOOD_TYPE_LIST (TYPEID,TYPENAME) values ('14','小吃、甜饼');
Insert into SYSTEM.FOOD_TYPE_LIST (TYPEID,TYPENAME) values ('15','速食食品');
Insert into SYSTEM.FOOD_TYPE_LIST (TYPEID,TYPENAME) values ('16','饮料类');
Insert into SYSTEM.FOOD_TYPE_LIST (TYPEID,TYPENAME) values ('17','含酒精饮料');
Insert into SYSTEM.FOOD_TYPE_LIST (TYPEID,TYPENAME) values ('18','糖、果脯和蜜饯、蜂蜜');
Insert into SYSTEM.FOOD_TYPE_LIST (TYPEID,TYPENAME) values ('19','油脂类');
Insert into SYSTEM.FOOD_TYPE_LIST (TYPEID,TYPENAME) values ('20','调味品类');
Insert into SYSTEM.FOOD_TYPE_LIST (TYPEID,TYPENAME) values ('21','其它');
--------------------------------------------------------
--  DDL for Index FOOD_TYPE_LIST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."FOOD_TYPE_LIST_PK" ON "SYSTEM"."FOOD_TYPE_LIST" ("TYPEID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table FOOD_TYPE_LIST
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."FOOD_TYPE_LIST" MODIFY ("TYPEID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."FOOD_TYPE_LIST" MODIFY ("TYPENAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."FOOD_TYPE_LIST" ADD CONSTRAINT "FOOD_TYPE_LIST_PK" PRIMARY KEY ("TYPEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
